services:
  postgres:
    image: postgres:latest
    container_name: authdb
#    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgres

  adminer:
    image: adminer
#    restart: always
    ports:
      - '5051:8080'

volumes:
  pgdata: