services:
  postgres:
    image: postgres:latest
    container_name: authdb
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - '5051:8080'

volumes:
  pgdata: